spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buptStore?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB #单个文件大小为10MB
      max-request-size: 100MB #多个文件大小为100MB
  data:
    redis:
#      host: 8.146.198.76
      port: 6379
#      password: 0613
      database: 0
      url: redis://0613@8.146.198.76:6379
      jedis:
        #redis连接池配置
        pool:
          max-active: 8 #最大连接数
          max-wait: 1ms #连接池最大阻塞等待时间
          max-idle: 4 #连接池中的最大空闲连接
          min-idle: 0 #连接池中的最小空闲连接
#  设置Redis缓存过期时间
#  cache:
#    redis:
#      time-to-live:



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package:

bupt:
  path: D:\IDEA project\java_project\buptStore\src\load\
  serverPath: /usr/local/app/buptStore/

alipay:
  # 买家账号
  customerId: xnopsv6312@sandbox.com
  # 应用ID，自己的APPID，收款账号即是APPID对应的支付宝账号
  appId: 9021000122686112
  # 商户的PID，卖家支付宝账号ID
  sellerId: 2088721003932836
  # 支付宝网关
  url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  # 商户私钥
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDDX28yVqbDB5Nl5BkNbMfV/3kc3BuBMBEV/H4wEwB4wGwsyDc4adCcFGXS2MXqACD6kiyHhI1jl2yWl3VmxHi/v1wCmr3g+43Xws8TVQvHpGLt2kI2I6LdknjTrPsj1jWXn8aK405y2KhBSpvLXXmvFOUycBhRhMvw74gNkgWgw0QxFqZj8Gr9H1EUgyCQG82NdRIpwHUYDrfNntGra6HazG8CrbjLjmoxGnvHUJ+Paggx7+RmU+CrgIFa/HtTka6b8Pd7QtAvpUKqtTri7c3ocODXTaacll55/Ki12nw8gah6KVx7Js5F4NAzNbKbO6JRlullqVU2WMVbI0QV0/p1AgMBAAECggEAO3nfERT9+VtiDN+unL6j60q1pQqAuQhX+zh9dccjGp+BjvR4kwzre8hd4x0oyv61C3LaaXr5y/q6DPIYxGtFUyI/MW/IJCiQWsGsZnc6edFaaIxMIc0hdJB1hgMgBR3d/MWgHIHsTNwWBKJg4T0YoSscRwmG7bIen79bzL3KRtECTnyjWgXdO2vgLR6C1iT1Myz224Z9J3OVcqs0aBYXc93jS/ByN4lvwY/VlbcGfvGqg39EiAVPLjn7zrMgCruYMIXf3Rj+veb4eAZg1Dpxw3Q6MwIjcRuWjTX1+sAjv+VDQLHzptXKiGttStOvmIa3kA2kR7vKYVp0HNdX9K0zYQKBgQD0GL5nHZvumQQPyUZ3YAc8cHdLKoAlh4UbOo8GH0TZ91TseRLr7tGbpxWAYZnMJOjDL3MengqQQcRPE2SNKPhBW8APesrjDdvRJZt8Y9aILbBjUobRaxXWYV0A1LAUfU4mVhjjExqoKUzFmn7bdNGWgmidwufrCM09MnINlqR0WQKBgQDM5m5e4gYe/MK8czlGIi/AkzSKnm7+5OUQBAIqyp8RkTM7U0RQeXpcom4brJZSNC/5/rsHxU/AvtF7uxpaNXwsDX5DFGkLPGCXzxn20ZSpSjhnj6C0bnoHzBcjwgj5E0XKj+JhF/X1Zpp193zMZQPKkHvbchkKB7UPrkmM4LcjfQKBgQC0f++cNKrv/rqgKcgv0hTHvqqYLK9iERp+jgjhEBJL07c6vjUdvhXFsgIWUxX1fX2Zh+bqxxcsoVVW3BJIx/j766rUR4rr532a5OJbU0B6pr5+U7JZ/YPCaXDqglxKanZ1psj0cVYO76tTm/Eeuv2Y/In7zvrMNFAAZuMr5S9q0QKBgFTtffnd/WOCqMSrjaXALcLIQRLjsGX+QeNthehuq5gAcxe336zrbQhQWwslcfkIoIoiRytlYTUm4nVCjB2v5ZPs09TB9PgvQmop8T0YiWHR3acvJREkaXgp471yg32Zu2fGU7Ki19Orf4I93oBprjSbxnqixDYgE7A4MUwvKDmRAoGBAKdt2ysqDFQXvGrreERiDHmvTUY0zZBos6I/NbXHejGAlGxqDFYsAcP9V8AxumXsJTtrnQGJZV3H5mXehcKJBKNXFca11gX89QrJagAsDLudIKR1TuXfO86Z2r7m9HLN4115f8Wwt3CRZQbxD1gcKA90zsMJwadRZlVSjz/pW9HI
  # 支付宝公钥
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArjTYqI1zhd6/xZ44ZxzR0/PACumYaRZAZISQ/MXcZcHjskuZS/KFuK17yhEtPMBMrdechbVE3E8VYQUGnFWWE+6euG50Zh6Zf90aO2fhTK66LrBralD6ToppCBaFczJlY4KtcO2/6I1nnxKuzKTF8AWQveR0rRNsjbJNkWCuvYOrzs7YrywYGJtrfFiAf8qq4lAQBjrCfYPfheY1MA9MtaVoONOfad7CMQ9y9ViI+4Ph4EDpHGf+tsDsCRK+1GHGj5O2SfQ8Mw/zKmmt1p8Q/C6voigGl1NLcafAxwQYRtW6dwsPt5Blse42JEUuGi/XO9G+aoJIFovmXuoHeYDHlwIDAQAB
  # 接口内容加密密钥
  contentKey: J7R3ROn+P0bo4FKY9ItHtw==
  # 页面跳转同步通知页面路径
  returnUrl: http://8.146.198.76:8080/front/page/pay-success.html
  # 服务器异步通知页面路径
  notifyUrl: http://8.146.198.76:8080/alipay/notify



